sudo: false
language: python
services:
  - docker
python:
  - 2.7
    #  - 3.4
  - 3.5
    #  - 3.6
os:
  - linux

install:
  - pip install tox-travis
script: tox
notifications:
  email: false
branches:
  only:
    - master
